Frontend/Models/ProductosViewModel.cs
using Backend.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Frontend.Models
{
    public class ProductosViewModel
    {
        [Key]
        [Display(Name = "ID")]
        public int ProductoID { get; set; }
        [Display(Name = "Codigo de producto")]
        [Required(ErrorMessage = "Debe ingresar el codigo")]
        [MinLength(3)]
        public string CodigoProducto { get; set; }
        [Display(Name = "Nombre")]
        [Required(ErrorMessage = "Debe ingresar el nombre")]
        [MinLength(5)]
        public string Nombre { get; set; }
        [Display(Name = "Tipo de producto")]
        [Required(ErrorMessage = "Debe ingresar el tipo")]
        public int TipoProductoID { get; set; }
        [Display(Name = "Descripcion")]
        [DataType(DataType.MultilineText)]
        public string Descripcion { get; set; }
        [Display(Name = "Imagen")]
        public string Imagen { get; set; }
        [Display(Name = "Estado")]
        public bool Estado { get; set; }
        public HttpPostedFileBase ArchivoImagen { get; set; }

        public TipoProducto TipoProducto { get; set; }
        public IEnumerable<TipoProducto> TipoProductos { get; set; }
        
    }
}

Frontend/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Backend.Clases;
using Backend.DAL;
using Backend.Entities;
using Frontend.Models;

namespace Frontend.Controllers
{
    [Authorize]
    public class ProductosController : Controller
    {
        private ProductosViewModel Convertir(ProductosActivos producto)
        {
            return new ProductosViewModel
            {
                ProductoID = producto.ProductoID,
                CodigoProducto = producto.CodigoProducto,
                Nombre = producto.Nombre,
                TipoProductoID = producto.TipoProductoID,
                Descripcion = producto.Descripcion,
                Imagen = producto.Imagen,
                Estado = producto.Estado
            };
        }
        private ProductosViewModel Convertir(Productos producto)
        {
            return new ProductosViewModel
            {
                ProductoID = producto.ProductoID,
                CodigoProducto = producto.CodigoProducto,
                Nombre = producto.Nombre,
                TipoProductoID = producto.TipoProductoID,
                Descripcion = producto.Descripcion,
                Imagen = producto.Imagen,
                Estado = producto.Estado
            };
        }
        private Productos Convertir(ProductosViewModel productoViewModel)
        {
            return new Productos
            {
                ProductoID = productoViewModel.ProductoID,
                CodigoProducto = productoViewModel.CodigoProducto,
                Nombre = productoViewModel.Nombre,
                TipoProductoID = productoViewModel.TipoProductoID,
                Descripcion = productoViewModel.Descripcion,
                Imagen = productoViewModel.Imagen,
                Estado = productoViewModel.Estado
            };
        }
        public ActionResult Index()
        {
            try
            {
                List<ProductosActivos> productos;
                using (UnidadDeTrabajo<ProductosActivos> Unidad = new UnidadDeTrabajo<ProductosActivos>(new BDContext()))
                {
                    productos = Unidad.genericDAL.GetAll().ToList();
                }
                List<ProductosViewModel> lista = new List<ProductosViewModel>();
                ProductosViewModel productoViewModel;
                foreach (var item in productos)
                {
                    productoViewModel = Convertir(item);

                    using (UnidadDeTrabajo<TipoProducto> Unidad = new UnidadDeTrabajo<TipoProducto>(new BDContext()))
                    {
                        productoViewModel.TipoProducto = Unidad.genericDAL.Get(productoViewModel.TipoProductoID);
                    }
                    lista.Add(productoViewModel);
                }
                //Mostrar mensajes
                ViewBag.Message = BLLUtilitarios.msj;
                BLLUtilitarios.msj = null;
                return View(lista);
            }
            catch (Exception)
            {
                TempData["TipoMensaje"] = "alert alert-danger";
                TempData["Mensaje"] = "Error al obtener lista";
                return RedirectToAction("Index", "Home");
            }
        }
        [Authorize(Roles = "Administrador")]
        public ActionResult Create()
        {
            try
            {
                ProductosViewModel productos = new ProductosViewModel { };
                using (UnidadDeTrabajo<TipoProducto> unidad = new UnidadDeTrabajo<TipoProducto>(new BDContext()))
                {
                    productos.TipoProductos = unidad.genericDAL.GetAll().ToList();
                }
                return View(productos);
            }
            catch (Exception)
            {
                TempData["TipoMensaje"] = "alert alert-danger";
                TempData["Mensaje"] = "Error al ver formulario";
                return RedirectToAction("Index");
            }
        }
        [Authorize(Roles = "Administrador")]
        [HttpPost]
        public ActionResult Create(ProductosViewModel productoViewModel)
        {
            try
            {
                bool a;
                productoViewModel.Estado = true;

                using (BDContext context = new BDContext())
                {
                    if (context.Productos.Where(c => c.CodigoProducto == productoViewModel.CodigoProducto).Count() > 0)
                    {
                        TempData["TipoMensaje"] = "alert alert-danger";
                        TempData["MensajeError"] = "Codigo de producto ya existe";
                        using (UnidadDeTrabajo<TipoProducto> unidad = new UnidadDeTrabajo<TipoProducto>(new BDContext()))
                        {
                            productoViewModel.TipoProductos = unidad.genericDAL.GetAll().ToList();
                        }
                        return View("Create", productoViewModel);
                    }
                }


                if (productoViewModel.ArchivoImagen != null)
                {
                    string name = Path.GetFileNameWithoutExtension(productoViewModel.ArchivoImagen.FileName);
                    string extension = Path.GetExtension(productoViewModel.ArchivoImagen.FileName);
                    name = name + DateTime.Now.ToString("yyyymmssfff") + extension;
                    productoViewModel.Imagen = "~/Archivos/Productos/" + name;
                    name = Path.Combine(Server.MapPath("~/Archivos/Productos/"), name);
                    productoViewModel.ArchivoImagen.SaveAs(name);
                }



                Productos producto = Convertir(productoViewModel);

                using (UnidadDeTrabajo<Productos> unidad = new UnidadDeTrabajo<Productos>(new BDContext()))
                {
                    unidad.genericDAL.Add(producto);
                    a = unidad.Complete();
                }
                //Mostrar El mensaje 
                /* if (a)
                 {
                     BLLUtilitarios.msj = "Se ha agregado un nuevo producto 1";
                 }
                 else
                 {

                     BLLUtilitarios.msj = "Error al agregar producto en la base de datos";
                 }*/
                 TempData["TipoMensaje"] = "alert alert-success";
                 TempData["Mensaje"] = "Product creado: " + productoViewModel.CodigoProducto;

               return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["TipoMensaje"] = "alert alert-danger";
                TempData["Mensaje"] = "Error al crear producto: " + ex.Message;
                return RedirectToAction("Index");
            }
        }
        [Authorize(Roles = "Administrador")]
        public ActionResult Edit(int? id)
        {
            try
            {
                if (id != null)
                {
                    Productos producto;
                    using (UnidadDeTrabajo<Productos> unidad = new UnidadDeTrabajo<Productos>(new BDContext()))
                    {
                        producto = unidad.genericDAL.Get((int)id);
                        if (!producto.Estado)
                        {
                            return RedirectToAction("Index");
                        }
                    }
                    ProductosViewModel productos = Convertir(producto);

                    TipoProducto tipoProducto;
                    List<TipoProducto> tipoProductos;
                    using (UnidadDeTrabajo<TipoProducto> unidad = new UnidadDeTrabajo<TipoProducto>(new BDContext()))
                    {
                        tipoProductos = unidad.genericDAL.GetAll().ToList();
                        tipoProducto = unidad.genericDAL.Get(productos.TipoProductoID);
                    }
                    productos.TipoProductos = tipoProductos;
                    return View(productos);
                }
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                TempData["TipoMensaje"] = "alert alert-danger";
                TempData["Mensaje"] = "Error al ver formulario";
                return RedirectToAction("Index");
            }
        }
        [Authorize(Roles = "Administrador")]
        [HttpPost]
        public ActionResult Edit(ProductosViewModel productoViewModel)
        {
            try
            {
                productoViewModel.Estado = true;
                if (productoViewModel.ArchivoImagen != null)
                {
                    string name = Path.GetFileNameWithoutExtension(productoViewModel.ArchivoImagen.FileName);
                    string extension = Path.GetExtension(productoViewModel.ArchivoImagen.FileName);
                    name = name + DateTime.Now.ToString("yyyymmssfff") + extension;
                    productoViewModel.Imagen = "~/Archivos/Productos/" + name;
                    name = Path.Combine(Server.MapPath("~/Archivos/Productos/"), name);
                    productoViewModel.ArchivoImagen.SaveAs(name);
                }

                using (UnidadDeTrabajo<Productos> unidad = new UnidadDeTrabajo<Productos>(new BDContext()))
                {
                    unidad.genericDAL.Update(Convertir(productoViewModel));
                    unidad.Complete();
                }
                TempData["TipoMensaje"] = "alert alert-success";
                TempData["Mensaje"] = "Product editado: " + productoViewModel.CodigoProducto;
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                TempData["TipoMensaje"] = "alert alert-danger";
                TempData["Mensaje"] = "Error al editar producto";
                return RedirectToAction("Index");
            }
        }
        public ActionResult Details(int? id)

Frontend/Views/Productos/Create.cshtml
@model Frontend.Models.ProductosViewModel

@{
    ViewBag.Title = "Crear producto";
}

<div class="row">
    <div class="col-lg">
        <div class="card shadow">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Crear</h6>
            </div>
            <div class="card-body">
                @using (Html.BeginForm("Create", "Productos", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @if (TempData["TipoMensaje"] != null)
                    {
                        <div class="@TempData["TipoMensaje"]">
                            <strong>@TempData["MensajeError"]</strong>
                        </div>
                    }
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-6">
                                @Html.LabelFor(model => model.CodigoProducto, htmlAttributes: new { @class = "control-label col-md-6 requerido" })

                                @Html.EditorFor(model => model.CodigoProducto, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.CodigoProducto, "", new { @class = "text-danger" })

                            </div>
                            <div class="col-md-6">
                                @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-6 requerido" })
                                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })

                            </div>

                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-6">
                                @Html.LabelFor(model => model.TipoProductoID, "Tipo de Producto", htmlAttributes: new { @class = "control-label col-md-6 requerido" })

                                @Html.DropDownListFor(model => model.TipoProductoID, new SelectList(Model.TipoProductos, "TipoProductoID", "Tipo"), "--Seleccione--", new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.TipoProductoID, "", new { @class = "text-danger" })
                            </div>

                            <div class="col-md-6">
                                @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-6" })
                                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                            </div>
                        </div>


                    </div>

                    <div class="form-group">
                        <div class="row">

                            <div class="col-md-6">
                                @Html.LabelFor(model => model.Imagen, htmlAttributes: new { @class = "control-label col-md-6" })
                                <input type="file" name="ArchivoImagen" class="form-control-file" accept="image/*" />
                                @Html.ValidationMessageFor(model => model.ArchivoImagen, "", new { @class = "text-danger" })
                            </div>
                        </div>


                    </div>

                    <div class="form-group">
                        <label style="color:red;">Los campos con * son requeridos</label>
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Crear" class="btn btn-primary" />
                            @Html.ActionLink("Regresar", "Index", null, new { @class = "btn btn-primary" })
                        </div>
                    </div>
                </div>
                }
                @section Scripts {
                    @Scripts.Render("~/bundles/jqueryval")
                }
            </div>
        </div>
    </div>
</div>

Frontend/Views/Productos/Delete.cshtml
@model Frontend.Models.ProductosViewModel

@{
    ViewBag.Title = "Eliminar producto";
}

<div class="row">
    <div class="col-lg">
        <div class="card shadow">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Borrar</h6>
            </div>
            <div class="card-body">
                <h3>¿Estas seguro que quieres borrar esto?</h3>
                <div>
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.CodigoProducto)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.CodigoProducto)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Nombre)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Nombre)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Descripcion)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Descripcion)
                        </dd>
                        @if (Model.Imagen != null)
                        {
                            <dt>
                                @Html.DisplayNameFor(model => model.Imagen)
                            </dt>

                            <dd>
                                <img src="@Url.Content(Model.Imagen)" width="250" height="250" />
                            </dd>
                        }

                        <dt>
                            @Html.DisplayNameFor(model => model.TipoProducto.Tipo)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.TipoProducto.Tipo)
                        </dd>

                    </dl>

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        @Html.HiddenFor(model => model.ProductoID)
                        <div class="form-actions no-color">
                            <input type="submit" value="Eliminar" class="btn btn-primary" />
                            @Html.ActionLink("Regresar", "Index", null, new { @class = "btn btn-primary" })
                        </div>
                    }
                </div>

            </div>
        </div>
    </div>
</div>

Frontend/Views/Productos/Details.cshtml
@model Frontend.Models.ProductosViewModel

@{
    ViewBag.Title = "Detalles de producto";
}

<div class="row">
    <div class="col-lg">
        <div class="card shadow">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Detalles</h6>
            </div>
            <div class="card-body">
                <div>
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.CodigoProducto)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.CodigoProducto)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Nombre)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Nombre)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Descripcion)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Descripcion)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.TipoProducto.Tipo)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.TipoProducto.Tipo)
                        </dd>
                        @if (Model.Imagen != null)
                        {
                            <dt>
                                @Html.DisplayNameFor(model => model.Imagen)
                            </dt>

                            <dd>
                                <img src="@Url.Content(Model.Imagen)" width="250" height="250"/>
                            </dd>
                        }
                    </dl>
                    <p>
                        @if (Roles.IsUserInRole("Administrador"))
                        {
                            @Html.ActionLink("Editar", "Edit", new { id = Model.ProductoID }, new { @class = "btn btn-primary" })
                        }
                            @Html.ActionLink("Regresar", "Index", null, new { @class = "btn btn-primary" })
                        </p>
                </div>
            </div>
        </div>
    </div>
</div>

Frontend/Views/Productos/Edit.cshtml
@model Frontend.Models.ProductosViewModel

@{
    ViewBag.Title = "Editar producto";
}

<div class="row">
    <div class="col-lg">
        <div class="card shadow">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Editar</h6>
            </div>
            <div class="card-body">


                @using (Html.BeginForm("Edit", "Productos", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.ProductoID)

                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-6">
                                @Html.LabelFor(model => model.CodigoProducto, htmlAttributes: new { @class = "control-label col-md-6 requerido" })

                                @Html.EditorFor(model => model.CodigoProducto, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                @Html.ValidationMessageFor(model => model.CodigoProducto, "", new { @class = "text-danger" })

                            </div>
                            <div class="col-md-6">
                                @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-6 requerido" })
                                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })

                            </div>

                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-6">
                                @Html.LabelFor(model => model.TipoProductoID, "Tipo de Producto", htmlAttributes: new { @class = "control-label col-md-6 requerido" })

                                @Html.DropDownListFor(model => model.TipoProductoID, new SelectList(Model.TipoProductos, "TipoProductoID", "Tipo"), new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.TipoProductoID, "", new { @class = "text-danger" })
                            </div>

                            <div class="col-md-6">
                                @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-6" })
                                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                            </div>
                        </div>


                    </div>

                    <div class="form-group">
                        <div class="row">

                            <div class="col-md-6">
                                @Html.LabelFor(model => model.Imagen, htmlAttributes: new { @class = "control-label col-md-6" })
                                <input type="file" name="ArchivoImagen" class="form-control-file" accept="image/*" />
                                @Html.ValidationMessageFor(model => model.ArchivoImagen, "", new { @class = "text-danger" })
                            </div>
                        </div>


                    </div>

                    <div class="form-group">
                        <label style="color:red;">Los campos con * son requeridos</label>
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Editar" class="btn btn-primary" />
                            @Html.ActionLink("Regresar", "Index", null, new { @class = "btn btn-primary" })
                        </div>
                    </div>
                </div>
                }
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Frontend/Views/Productos/Index.cshtml
@model IEnumerable<Frontend.Models.ProductosViewModel>

@{
    ViewBag.Title = "Lista de productos";
}
@if (ViewBag.Message != null)
{
    <script>
        window.onload = function ()
        {
            var text = "@ViewBag.Message";
            if (text.charAt(text.length - 1) == 1) {
                swal({
                    title: "¡" + text.slice(0, -1) + "correctamente!",
                    icon: "success",
                    button: "OK",
                });

            }
            else {
                swal({
                    title: "¡" + text + "!",
                    icon: "error",
                    button: "OK",
                });

            }
        };

    </script>

}

<div class="row">
    <div class="col-lg">
        <div class="card shadow" style="padding:1%">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Lista</h6>
            </div>
            @if (Roles.IsUserInRole("Administrador"))
            {
                <p class="p-3">
                    @Html.ActionLink("Crear", "Create", null, new { @class = "btn btn-primary" })
                </p>
            }
                @if (TempData["TipoMensaje"] != null)
                {
                    <div class="@TempData["TipoMensaje"]">
                        <strong>@TempData["Mensaje"]</strong>
                    </div>
                }
                <table id="listadatatable" class="table compact">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.CodigoProducto)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Nombre)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.TipoProducto.Tipo)
                            </th>
                            <th></th>
                        </tr>
                    </thead>

                    <tbody>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CodigoProducto)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Nombre)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.TipoProducto.Tipo)
                                </td>
                                <td>
                                    @if (Roles.IsUserInRole("Administrador"))
                                    {
                                        <a href="@Url.Action("Edit", new { id = item.ProductoID })" class="btn btn-success btn-circle">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                    }
                                    <a href="@Url.Action("Details",  new { id = item.ProductoID })" class="btn btn-info btn-circle">
                                        <i class="fas fa-info-circle"></i>
                                    </a>
                                    @if (Roles.IsUserInRole("Administrador"))
                                    {
                                        <a href="@Url.Action("Delete", new { id = item.ProductoID })" class="btn btn-danger btn-circle">
                                            <i class="fas fa-trash"></i>
                                        </a>
                                    }
                                    </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
    </div>
</div>