Frontend/Controllers/GraficosController.cs
using Backend.DAL;
using Backend.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Frontend.Controllers
{
    [Authorize]
    public class GraficosController : Controller
    {
        // GET: Graficos
        public ActionResult _GraficoDona()
        {

            using (BDContext context = new BDContext())
            {
                sp_GraficoPedidos_Result graficoPedidos = context.sp_GraficoPedidos().FirstOrDefault();
            

                return PartialView(graficoPedidos);
            }
        }

        protected override void OnException(ExceptionContext filterContext)
        {
            filterContext.ExceptionHandled = true;

            //Log the error!!

            //Redirect to action
            filterContext.Result = RedirectToAction("Index", "Error");
        }

    }
}

Frontend/Controllers/HomeController.cs
using Backend.Clases;
using Backend.DAL;
using Backend.Entities;
using Frontend.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Frontend.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private UsuarioViewModel Convertir(UsuariosActivos usuario)
        {
            return new UsuarioViewModel
            {
                UsuarioID = usuario.UsuarioID,
                Identificacion = usuario.Identificacion,
                UserName = usuario.UserName,
                Password = usuario.Password,
                NombreCompleto = usuario.NombreCompleto,
                Telefono = usuario.Telefono,
                Correo = usuario.Correo,
                Direccion = usuario.Direccion,
                Estado = usuario.Estado
            };
        }
        private UsuarioViewModel Convertir(Usuarios usuario)
        {
            return new UsuarioViewModel
            {
                UsuarioID = usuario.UsuarioID,
                Identificacion = usuario.Identificacion,
                UserName = usuario.UserName,
                Password = usuario.Password,
                NombreCompleto = usuario.NombreCompleto,
                Telefono = usuario.Telefono,
                Correo = usuario.Correo,
                Direccion = usuario.Direccion,
                Estado = usuario.Estado
            };
        }
        private Usuarios Convertir(UsuarioViewModel usuarioViewModel)
        {
            return new Usuarios
            {
                UsuarioID = usuarioViewModel.UsuarioID,
                Identificacion = usuarioViewModel.Identificacion,
                UserName = usuarioViewModel.UserName,
                Password = usuarioViewModel.Password,
                NombreCompleto = usuarioViewModel.NombreCompleto,
                Telefono = usuarioViewModel.Telefono,
                Correo = usuarioViewModel.Correo,
                Direccion = usuarioViewModel.Direccion,
                Estado = usuarioViewModel.Estado
            };
        }


        public ActionResult Index()
        {
           return View();
        }
     /*   public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }*/

        public ActionResult MyAccount()
        {
            try
            {
                Usuarios usuario;
                using (UnidadDeTrabajo<Usuarios> unidad = new UnidadDeTrabajo<Usuarios>(new BDContext()))
                {
                    usuario = unidad.genericDAL.Get((int)Session["userID"]);
                    if (!usuario.Estado)
                    {
                        return RedirectToAction("Index");
                    }
                }
                UsuarioViewModel usuarios = Convertir(usuario);
                return View(usuarios);
            }
            catch (Exception)
            {
                TempData["TipoMensaje"] = "alert alert-danger";
                TempData["Mensaje"] = "Error al obtener datos de usuario";
                return RedirectToAction("Index", "Home");
            }
        }
        [HttpPost]
        public ActionResult MyAccount(UsuarioViewModel usuarioViewModel)
        {
            try
            {
                Usuarios usuario;
                using (UnidadDeTrabajo<Usuarios> unidad = new UnidadDeTrabajo<Usuarios>(new BDContext()))
                {
                    usuario = unidad.genericDAL.Get(usuarioViewModel.UsuarioID);
                    usuario.Identificacion = usuarioViewModel.Identificacion;
                    usuario.NombreCompleto = usuarioViewModel.NombreCompleto;
                    usuario.Telefono = usuarioViewModel.Telefono;
                    usuario.Correo = usuarioViewModel.Correo;
                    usuario.Direccion = usuario.Direccion;
                    unidad.genericDAL.Update(usuario);
                    unidad.Complete();
                }
                TempData["TipoMensaje"] = "alert alert-success";
                TempData["Mensaje"] = "Datos actualizados";
                return RedirectToAction("Index");

            }
            catch (Exception)
            {
                TempData["TipoMensaje"] = "alert alert-danger";
                TempData["Mensaje"] = "Error al actualizar datos";
                return RedirectToAction("Index","Home");
            }
        }
        public ActionResult ChangePassword()
        {
            try
            {
                Usuarios usuario;
                using (UnidadDeTrabajo<Usuarios> unidad = new UnidadDeTrabajo<Usuarios>(new BDContext()))
                {
                    usuario = unidad.genericDAL.Get((int)Session["userID"]);
                    if (!usuario.Estado)
                    {
                        return RedirectToAction("Index");
                    }
                }
                UsuarioViewModel usuarios = Convertir(usuario);
                using (UnidadDeTrabajo<Roles> unidad = new UnidadDeTrabajo<Roles>(new BDContext()))
                {
                    usuarios.Roles = unidad.genericDAL.GetAll();
                    unidad.Complete();
                }
                usuarios.Password = "";
                //List De tipoa de usuario

                return View(usuarios);
            }
            catch (Exception)
            {
                TempData["TipoMensaje"] = "alert alert-danger";
                TempData["Mensaje"] = "Error al cambiar contraseña";
                return RedirectToAction("Index", "Home");
            }
        }
        [HttpPost]
        public ActionResult ChangePassword(UsuarioViewModel usuarioViewModel)
        {
            try
            {
                using (UnidadDeTrabajo<Usuarios> unidad = new UnidadDeTrabajo<Usuarios>(new BDContext()))
                {
                    Usuarios usuario = unidad.genericDAL.Get(usuarioViewModel.UsuarioID);

                    if (BLLUtilitarios.getHashSha256(usuarioViewModel.Password) == usuario.Password)
                    {
                        if (usuarioViewModel.NewPassword == usuarioViewModel.RepeatPassword)
                        {
                            if (BLLUtilitarios.PasswordValida(usuarioViewModel.NewPassword))
                            {
                                usuario.Password = BLLUtilitarios.getHashSha256(usuarioViewModel.NewPassword);
                                unidad.genericDAL.Update(usuario);
                                unidad.Complete();
                                TempData["TipoMensaje"] = "alert alert-success";
                                TempData["Mensaje"] = "Cambio de contraseña correcto";
                                return RedirectToAction("Index");
                            }
                            TempData["TipoMensaje"] = "alert alert-danger";
                            TempData["Mensaje"] = "No cumple politicas: " + BLLUtilitarios.MensajePoliticasPassword();
                            return RedirectToAction("ChangePassword", new { @id = usuario.UsuarioID });
                        }
                        TempData["TipoMensaje"] = "alert alert-danger";
                        TempData["MensajeError"] = "Repita la contraseña";
                        return RedirectToAction("ChangePassword", new { @id = usuario.UsuarioID });
                    }
                    TempData["TipoMensaje"] = "alert alert-danger";
                    TempData["MensajeError"] = "Contraseña incorrecta";
                    return RedirectToAction("ChangePassword", new { @id = usuario.UsuarioID });
                }
            }
            catch (Exception)
            {
                TempData["TipoMensaje"] = "alert alert-danger";
                TempData["Mensaje"] = "Error al cambiar contraseña";
                return RedirectToAction("Index", "Home");
            }
        }

      /*  protected override void OnException(ExceptionContext filterContext)
        {
            filterContext.ExceptionHandled = true;

            //Log the error!!

            //Redirect to action
            filterContext.Result = RedirectToAction("Index", "Error");
        }*/
    }
}

Frontend/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Frontend/Views/Home/ChangePassword.cshtml
@model Frontend.Models.UsuarioViewModel

@{
    ViewBag.Title = "ChangePassword";
}

<div class="row">
    <div class="col-lg">
        <div class="card shadow">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Cambiar contraseña</h6>
            </div>
            <div class="card-body">

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.UsuarioID)
                    @if (TempData["TipoMensaje"] != null)
                    {
                        <div class="@TempData["TipoMensaje"]">
                            <strong>@TempData["Mensaje"]</strong>
                        </div>
                    }


                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-6">
                                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-6 requerido" })

                                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                            </div>
                            <div class="col-md-6">
                                @Html.LabelFor(model => model.NewPassword, htmlAttributes: new { @class = "control-label col-md-6 requerido" })

                                @Html.EditorFor(model => model.NewPassword, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.NewPassword, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        
                    </div>

                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-6">
                                @Html.LabelFor(model => model.RepeatPassword, htmlAttributes: new { @class = "control-label col-md-6 requerido" })

                                @Html.EditorFor(model => model.RepeatPassword, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.RepeatPassword, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        
                    </div>

                    <div class="form-group">
                        <label style="color:red;">Los campos con * son requeridos</label>
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Cambiar contraseña" class="btn btn-primary" />
                            @Html.ActionLink("Regresar", "Index", null, new { @class = "btn btn-primary" })
                        </div>
                    </div>
                </div>
                }
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Frontend/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Frontend/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Dashboard";
}

<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
   
</div>

<!-- Content Row -->
<div class="row">

    @if (TempData["TipoMensaje"] != null)
    {
        <div class="@TempData["TipoMensaje"]">
            <strong>@TempData["Mensaje"]</strong>
        </div>
    }

   
</div>

<!-- Content Row -->

<div class="row">

    <!-- Area Chart -->
    <div class="col-xl-6 col-lg-6">
        @Html.Action("_GraficoMensualProduccion", "GraficoLineasProduccion")

    </div>

    <!-- Pie Chart -->
    <div class="col-xl-6 col-lg- 6">
        @Html.Action("_GraficoDona", "Graficos")
    </div>
</div>



<div class="row">

    <!-- Area Chart -->
    <div class="col-xl-6 col-lg-6">
        @Html.Action("_GraficoParettoMerma", "GraficoParettoMerma")

    </div>

    <!-- Pie Chart -->
    <div class="col-xl-6 col-lg- 6">
        
    </div>
</div>

Frontend/Views/Home/MyAccount.cshtml
@model Frontend.Models.UsuarioViewModel

@{
    ViewBag.Title = "Editar Usuario";
}
<div class="row">
    <div class="col-lg">
        <div class="card shadow">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Mi cuenta</h6>
            </div>
            <div class="card-body">

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.UsuarioID)
                    @if (TempData["TipoMensaje"] != null)
                    {
                        <div class="@TempData["TipoMensaje"]">
                            <strong>@TempData["Mensaje"]</strong>
                        </div>
                    }
                    <p class="p-3">
                        @Html.ActionLink("Cambiar contraseña", "ChangePassword", null, new { @class = "btn btn-primary" })
                    </p>
                    <div class="form-group">

                        <div class="row">
                            <div class="col-md-6">
                                @Html.LabelFor(model => model.Identificacion, htmlAttributes: new { @class = "control-label col-md-6 requerido" })

                                @Html.EditorFor(model => model.Identificacion, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                @Html.ValidationMessageFor(model => model.Identificacion, "", new { @class = "text-danger" })
                            </div>
                            <div class="col-md-6">
                                @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-6 requerido" })

                                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        
                    </div>

                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-6">
                                @Html.LabelFor(model => model.NombreCompleto, htmlAttributes: new { @class = "control-label col-md-6 requerido" })

                                @Html.EditorFor(model => model.NombreCompleto, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.NombreCompleto, "", new { @class = "text-danger" })
                            </div>
                            <div class="col-md-6">
                                @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-6 requerido" })

                                @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        
                    </div>

                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-6">
                                @Html.LabelFor(model => model.Correo, htmlAttributes: new { @class = "control-label col-md-6 requerido" })

                                @Html.EditorFor(model => model.Correo, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                @Html.ValidationMessageFor(model => model.Correo, "", new { @class = "text-danger" })
                            </div>
                            <div class="col-md-6">
                                @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-6" })

                                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        
                    </div>
                    <div class="form-group">
                        <label style="color:red;">Los campos con * son requeridos</label>
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Cambiar informacion" class="btn btn-primary" />
                            @Html.ActionLink("Regresar", "Index", null, new { @class = "btn btn-primary" })
                        </div>
                    </div>
                </div>
                }
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}