Frontend/Models/FichaTecnicaBotellaViewModel.cs
using Backend.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Frontend.Models
{
    public class FichaTecnicaBotellaViewModel
    {
        [Key]
        [Display(Name = "ID")]
        public int FichaTecnicaBotellaID { get; set; }
        [Display(Name = "Producto")]
        [Required(ErrorMessage = "Debe ingresar el producto")]
        public int ProductoID { get; set; }
        [Display(Name = "Altura (milimetros)")]
        [Required(ErrorMessage = "Debe ingresar la altura")]
        public double Altura { get; set; }
        [Display(Name = "Diametro mayor (milimetros)")]
        [Required(ErrorMessage = "Debe ingresar el diametro mayor")]
        public double DiametroMayor { get; set; }
        [Display(Name = "Diametro menor (milimetros)")]
        [Required(ErrorMessage = "Debe ingresar el diametro menor")]
        public double DiametroMenor { get; set; }
        [Display(Name = "Diametro cuello (milimetros)")]
        [Required(ErrorMessage = "Debe ingresar el diametro del cuello")]
        public double DiametroCuello { get; set; }
        [Display(Name = "Capacidad volumetrica (mililitros)")]
        [Required(ErrorMessage = "Debe ingresar la capacidad volumetrica")]
        public double CapacidadVolumetrica { get; set; }
        [Display(Name = "Tolerancia")]
        public Nullable<double> Tolerancia { get; set; }
        [Display(Name = "Imagen cuerpo")]
     //   [DataType(DataType.ImageUrl)]
        public string ImagenCuerpo { get; set; }
        [Display(Name = "Imagen fondo")]
     //   [DataType(DataType.ImageUrl)]
        public string ImagenFondo { get; set; }
        [Display(Name = "Estado")]
        public bool Estado { get; set; }
        public HttpPostedFileBase ArchivoImagenCuerpo { get; set; }
        public HttpPostedFileBase ArchivoImagenFondo { get; set; }
        public Productos Producto { get; set; }
        public IEnumerable<ProductosBotellaActivos> Productos { get; set; }
    }
}

Frontend/Controllers/FichaTecnicaBotellaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Backend.Clases;
using Backend.DAL;
using Backend.Entities;
using Frontend.Models;

namespace Frontend.Controllers
{
    [Authorize]
    public class FichaTecnicaBotellaController : Controller
    {
        private FichaTecnicaBotellaViewModel Convertir(FichaTecnicaBotellaActivos fichaTecnicaBotella)
        {
            return new FichaTecnicaBotellaViewModel
            {
                FichaTecnicaBotellaID = fichaTecnicaBotella.FichaTecnicaBotellaID,
                ProductoID = fichaTecnicaBotella.ProductoID,
                Altura = fichaTecnicaBotella.Altura,
                DiametroMayor = fichaTecnicaBotella.DiametroMayor,
                DiametroMenor = fichaTecnicaBotella.DiametroMenor,
                DiametroCuello = fichaTecnicaBotella.DiametroCuello,
                CapacidadVolumetrica = fichaTecnicaBotella.CapacidadVolumetrica,
                Tolerancia = fichaTecnicaBotella.Tolerancia,
                ImagenCuerpo = fichaTecnicaBotella.ImagenCuerpo,
                ImagenFondo = fichaTecnicaBotella.ImagenFondo,
                Estado = fichaTecnicaBotella.Estado
            };
        }


        private FichaTecnicaBotellaViewModel Convertir(FichaTecnicaBotella fichaTecnicaBotella)
        {
            return new FichaTecnicaBotellaViewModel
            {
                FichaTecnicaBotellaID = fichaTecnicaBotella.FichaTecnicaBotellaID,
                ProductoID = fichaTecnicaBotella.ProductoID,
                Altura = fichaTecnicaBotella.Altura,
                DiametroMayor = fichaTecnicaBotella.DiametroMayor,
                DiametroMenor = fichaTecnicaBotella.DiametroMenor,
                DiametroCuello = fichaTecnicaBotella.DiametroCuello,
                CapacidadVolumetrica = fichaTecnicaBotella.CapacidadVolumetrica,
                Tolerancia = fichaTecnicaBotella.Tolerancia,
                ImagenCuerpo = fichaTecnicaBotella.ImagenCuerpo,
                ImagenFondo = fichaTecnicaBotella.ImagenFondo,
                Estado = fichaTecnicaBotella.Estado
            };
        }
        private FichaTecnicaBotella Convertir(FichaTecnicaBotellaViewModel fichaTecnicaBotellaViewModel)
        {
            return new FichaTecnicaBotella
            {
                FichaTecnicaBotellaID = fichaTecnicaBotellaViewModel.FichaTecnicaBotellaID,
                ProductoID = fichaTecnicaBotellaViewModel.ProductoID,
                Altura = fichaTecnicaBotellaViewModel.Altura,
                DiametroMayor = fichaTecnicaBotellaViewModel.DiametroMayor,
                DiametroMenor = fichaTecnicaBotellaViewModel.DiametroMenor,
                DiametroCuello = fichaTecnicaBotellaViewModel.DiametroCuello,
                CapacidadVolumetrica = fichaTecnicaBotellaViewModel.CapacidadVolumetrica,
                Tolerancia = fichaTecnicaBotellaViewModel.Tolerancia,
                ImagenCuerpo = fichaTecnicaBotellaViewModel.ImagenCuerpo,
                ImagenFondo = fichaTecnicaBotellaViewModel.ImagenFondo,
                Estado = fichaTecnicaBotellaViewModel.Estado
            };
        }
        public ActionResult Index()
        {
            try
            {
                List<FichaTecnicaBotellaActivos> fichaTecnicaBotellas;
                using (UnidadDeTrabajo<FichaTecnicaBotellaActivos> Unidad = new UnidadDeTrabajo<FichaTecnicaBotellaActivos>(new BDContext()))
                {
                    fichaTecnicaBotellas = Unidad.genericDAL.GetAll().ToList();
                }
                List<FichaTecnicaBotellaViewModel> lista = new List<FichaTecnicaBotellaViewModel>();
                FichaTecnicaBotellaViewModel fichaTecnicaBotellaViewModel;
                foreach (var item in fichaTecnicaBotellas)
                {
                    fichaTecnicaBotellaViewModel = Convertir(item);
                    using (UnidadDeTrabajo<Productos> Unidad = new UnidadDeTrabajo<Productos>(new BDContext()))
                    {
                        fichaTecnicaBotellaViewModel.Producto = Unidad.genericDAL.Get(fichaTecnicaBotellaViewModel.ProductoID);
                    }
                    lista.Add(fichaTecnicaBotellaViewModel);
                }
                //Mostrar mensajes
                ViewBag.Message = BLLUtilitarios.msj;
                BLLUtilitarios.msj = null;
                return View(lista);
            }
            catch (Exception)
            {
                TempData["TipoMensaje"] = "alert alert-danger";
                TempData["Mensaje"] = "Error al obtener lista";
                return RedirectToAction("Index", "Home");
            }
        }
        [Authorize(Roles = "Administrador")]
        public ActionResult Create()
        {
            try
            {
                FichaTecnicaBotellaViewModel fichaTecnicaBotellaViewModel = new FichaTecnicaBotellaViewModel { };
                using (UnidadDeTrabajo<ProductosBotellaActivos> unidad = new UnidadDeTrabajo<ProductosBotellaActivos>(new BDContext()))
                {
                    fichaTecnicaBotellaViewModel.Productos = unidad.genericDAL.GetAll().ToList();
                }
                return View(fichaTecnicaBotellaViewModel);
            }
            catch (Exception)
            {
                TempData["TipoMensaje"] = "alert alert-danger";
                TempData["Mensaje"] = "Error al ver formulario";
                return RedirectToAction("Index");
            }
        }
        [Authorize(Roles = "Administrador")]
        [HttpPost]
        public ActionResult Create(FichaTecnicaBotellaViewModel fichaTecnicaBotellaViewModel)
        {
            try
            {
                bool a;
                fichaTecnicaBotellaViewModel.Estado = true;
                if (fichaTecnicaBotellaViewModel.ArchivoImagenCuerpo != null)
                {
                    string name = Path.GetFileNameWithoutExtension(fichaTecnicaBotellaViewModel.ArchivoImagenCuerpo.FileName);
                    string extension = Path.GetExtension(fichaTecnicaBotellaViewModel.ArchivoImagenCuerpo.FileName);
                    name = name + DateTime.Now.ToString("yyyymmssfff") + extension;
                    fichaTecnicaBotellaViewModel.ImagenCuerpo = "~/Archivos/FichaTecnicaBotella/" + name;
                    name = Path.Combine(Server.MapPath("~/Archivos/FichaTecnicaBotella/"), name);
                    fichaTecnicaBotellaViewModel.ArchivoImagenCuerpo.SaveAs(name);
                }
                if (fichaTecnicaBotellaViewModel.ArchivoImagenFondo != null)
                {
                    string name = Path.GetFileNameWithoutExtension(fichaTecnicaBotellaViewModel.ArchivoImagenFondo.FileName);
                    string extension = Path.GetExtension(fichaTecnicaBotellaViewModel.ArchivoImagenFondo.FileName);
                    name = name + DateTime.Now.ToString("yyyymmssfff") + extension;
                    fichaTecnicaBotellaViewModel.ImagenFondo = "~/Archivos/FichaTecnicaBotella/" + name;
                    name = Path.Combine(Server.MapPath("~/Archivos/FichaTecnicaBotella/"), name);
                    fichaTecnicaBotellaViewModel.ArchivoImagenFondo.SaveAs(name);
                }


                FichaTecnicaBotella fichaTecnicaBotella = Convertir(fichaTecnicaBotellaViewModel);
                using (UnidadDeTrabajo<FichaTecnicaBotella> unidad = new UnidadDeTrabajo<FichaTecnicaBotella>(new BDContext()))
                {
                    unidad.genericDAL.Add(fichaTecnicaBotella);
                    a = unidad.Complete();
                }
                //Mostrar El mensaje 
             /*  if (a)
                {
                 
                }
                else
                {

                  
                }*/

                TempData["TipoMensaje"] = "alert alert-success";
                TempData["Mensaje"] = "Ficha tecnica creada";
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                TempData["TipoMensaje"] = "alert alert-danger";
                TempData["Mensaje"] = "Error al agregar ficha tecnica";
                return RedirectToAction("Index");
            }
        }
        [Authorize(Roles = "Administrador")]
        public ActionResult Edit(int? id)
        {
            try
            {
                if (id != null)
                {
                    FichaTecnicaBotella fichaTecnicaBotella;
                    using (UnidadDeTrabajo<FichaTecnicaBotella> unidad = new UnidadDeTrabajo<FichaTecnicaBotella>(new BDContext()))
                    {
                        fichaTecnicaBotella = unidad.genericDAL.Get((int)id);
                        if (!fichaTecnicaBotella.Estado)
                        {
                            return RedirectToAction("Index");
                        }
                    }
                    FichaTecnicaBotellaViewModel fichaTecnicaBotellaViewModel = Convertir(fichaTecnicaBotella);
                    List<ProductosBotellaActivos> productos;
                    using (UnidadDeTrabajo<ProductosBotellaActivos> unidad = new UnidadDeTrabajo<ProductosBotellaActivos>(new BDContext()))
                    {
                        productos = unidad.genericDAL.GetAll().ToList();
                    }
                    fichaTecnicaBotellaViewModel.Productos = productos;
                    return View(fichaTecnicaBotellaViewModel);
                }
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                TempData["TipoMensaje"] = "alert alert-danger";
                TempData["Mensaje"] = "Error al ver formulario";
                return RedirectToAction("Index");
            }
        }
        [Authorize(Roles = "Administrador")]
        [HttpPost]

Frontend/Views/FichaTecnicaBotella/Create.cshtml
@model Frontend.Models.FichaTecnicaBotellaViewModel

@{
    ViewBag.Title = "Crear ficha tecnica botella";
}


<div class="row">
    <div class="col-lg">
        <div class="card shadow">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Crear</h6>
            </div>
            <div class="card-body">

                @using (Html.BeginForm("Create", "FichaTecnicaBotella", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-6">
                                    @Html.LabelFor(model => model.ProductoID, "Producto", htmlAttributes: new { @class = "control-label col-md-6 requerido" })

                                    @Html.DropDownListFor(model => model.ProductoID, new SelectList(Model.Productos, "ProductoID", "Nombre"), "--Seleccione--", new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.ProductoID, "", new { @class = "text-danger" })
                                </div>
                                <div class="col-md-6">
                                    @Html.LabelFor(model => model.Altura, htmlAttributes: new { @class = "control-label col-md-6 requerido" })

                                    @Html.EditorFor(model => model.Altura, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Altura, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            
                        </div>

                      

                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-6">
                                    @Html.LabelFor(model => model.DiametroMayor, htmlAttributes: new { @class = "control-label col-md-6 requerido" })

                                    @Html.EditorFor(model => model.DiametroMayor, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.DiametroMayor, "", new { @class = "text-danger" })
                                </div>
                                <div class="col-md-6">
                                    @Html.LabelFor(model => model.DiametroMenor, htmlAttributes: new { @class = "control-label col-md-6 requerido" })

                                    @Html.EditorFor(model => model.DiametroMenor, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.DiametroMenor, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            
                        </div>

                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-6">
                                    @Html.LabelFor(model => model.DiametroCuello, htmlAttributes: new { @class = "control-label col-md-6 requerido" })

                                    @Html.EditorFor(model => model.DiametroCuello, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.DiametroCuello, "", new { @class = "text-danger" })
                                </div>
                                <div class="col-md-6">
                                    @Html.LabelFor(model => model.CapacidadVolumetrica, htmlAttributes: new { @class = "control-label col-md-8 requerido" })
                                    @Html.EditorFor(model => model.CapacidadVolumetrica, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.CapacidadVolumetrica, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            
                        </div>

                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-6">
                                    @Html.LabelFor(model => model.ImagenFondo, htmlAttributes: new { @class = "control-label col-md-6" })

                                    <input type="file" name="ArchivoImagenFondo" class="form-control-file" accept="image/*" />
                                    @Html.ValidationMessageFor(model => model.ArchivoImagenFondo, "", new { @class = "text-danger" })

                                </div>
                                <div class="col-md-6">
                                    @Html.LabelFor(model => model.ImagenCuerpo, htmlAttributes: new { @class = "control-label col-md-6" })

                                    <input type="file" name="ArchivoImagenCuerpo" class="form-control-file" accept="image/*" />
                                    @Html.ValidationMessageFor(model => model.ArchivoImagenCuerpo, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-6">
                                    @Html.LabelFor(model => model.Tolerancia, htmlAttributes: new { @class = "control-label col-md-6" })

                                    @Html.EditorFor(model => model.Tolerancia, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Tolerancia, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label style="color:red;">Los campos con * son requeridos</label>
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Crear" class="btn btn-primary" />
                                @Html.ActionLink("Regresar", "Index", null, new { @class = "btn btn-primary" })
                            </div>
                        </div>
                    </div>
                }

                @section Scripts {
                    @Scripts.Render("~/bundles/jqueryval")
                }
            </div>
        </div>
    </div>
</div>

Frontend/Views/FichaTecnicaBotella/Delete.cshtml
@model Frontend.Models.FichaTecnicaBotellaViewModel

@{
    ViewBag.Title = "Eliminar ficha tecnica botella";
}

<div class="row">
    <div class="col-lg">
        <div class="card shadow">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Borrar</h6>
            </div>
            <div class="card-body">
                <h3>¿Estas seguro que quieres borrar esto?</h3>
                <div>
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Altura)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Altura)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.DiametroMayor)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.DiametroMayor)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.DiametroMenor)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.DiametroMenor)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.DiametroCuello)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.DiametroCuello)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.CapacidadVolumetrica)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.CapacidadVolumetrica)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Tolerancia)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Tolerancia)
                        </dd>

                        @if (Model.ImagenCuerpo != null)
                        {
                            <dt>
                                @Html.DisplayNameFor(model => model.ImagenCuerpo)
                            </dt>

                            <dd>
                                <img src="@Url.Content(Model.ImagenCuerpo)" width="250" height="250" />
                            </dd>
                        }

                        @if (Model.ImagenFondo != null)
                        {
                            <dt>
                                @Html.DisplayNameFor(model => model.ImagenFondo)
                            </dt>

                            <dd>
                                <img src="@Url.Content(Model.ImagenFondo)" width="250" height="250" />
                            </dd>
                        }

                        <dt>
                            @Html.DisplayNameFor(model => model.Producto.CodigoProducto)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Producto.CodigoProducto)
                        </dd>

                    </dl>

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        @Html.HiddenFor(model => model.FichaTecnicaBotellaID)
                        <div class="form-actions no-color">
                            <input type="submit" value="Eliminar" class="btn btn-primary" />
                            @Html.ActionLink("Regresar", "Index", null, new { @class = "btn btn-primary" })
                        </div>
                    }
                </div>

            </div>
        </div>
    </div>
</div>

Frontend/Views/FichaTecnicaBotella/Edit.cshtml
@model Frontend.Models.FichaTecnicaBotellaViewModel

@{
    ViewBag.Title = "Editar ficha tecnica botella";
}

<div class="row">
    <div class="col-lg">
        <div class="card shadow">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Editar</h6>
            </div>
            <div class="card-body">

                @using (Html.BeginForm("Edit", "FichaTecnicaBotella", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.FichaTecnicaBotellaID)

                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-6">
                                @Html.LabelFor(model => model.ProductoID, "Producto", htmlAttributes: new { @class = "control-label col-md-6 requerido" })

                                @Html.DropDownListFor(model => model.ProductoID, new SelectList(Model.Productos, "ProductoID", "Nombre"), new { @class = "form-control", @disabled = "disabled" })
                                @Html.ValidationMessageFor(model => model.ProductoID, "", new { @class = "text-danger" })
                            </div>
                            <div class="col-md-6">
                                @Html.LabelFor(model => model.Altura, htmlAttributes: new { @class = "control-label col-md-6 requerido" })

                                @Html.EditorFor(model => model.Altura, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Altura, "", new { @class = "text-danger" })
                            </div>
                        </div>

                    </div>



                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-6">
                                @Html.LabelFor(model => model.DiametroMayor, htmlAttributes: new { @class = "control-label col-md-6 requerido" })

                                @Html.EditorFor(model => model.DiametroMayor, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.DiametroMayor, "", new { @class = "text-danger" })
                            </div>
                            <div class="col-md-6">
                                @Html.LabelFor(model => model.DiametroMenor, htmlAttributes: new { @class = "control-label col-md-6 requerido" })

                                @Html.EditorFor(model => model.DiametroMenor, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.DiametroMenor, "", new { @class = "text-danger" })
                            </div>
                        </div>

                    </div>

                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-6">
                                @Html.LabelFor(model => model.DiametroCuello, htmlAttributes: new { @class = "control-label col-md-6 requerido" })

                                @Html.EditorFor(model => model.DiametroCuello, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.DiametroCuello, "", new { @class = "text-danger" })
                            </div>
                            <div class="col-md-6">
                                @Html.LabelFor(model => model.CapacidadVolumetrica, htmlAttributes: new { @class = "control-label col-md-8 requerido" })
                                @Html.EditorFor(model => model.CapacidadVolumetrica, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.CapacidadVolumetrica, "", new { @class = "text-danger" })
                            </div>
                        </div>

                    </div>

                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-6">
                                @Html.LabelFor(model => model.ImagenFondo, htmlAttributes: new { @class = "control-label col-md-6" })

                                <input type="file" name="ArchivoImagenFondo" class="form-control-file" accept="image/*" />
                                @Html.ValidationMessageFor(model => model.ArchivoImagenFondo, "", new { @class = "text-danger" })

                            </div>
                            <div class="col-md-6">
                                @Html.LabelFor(model => model.ImagenCuerpo, htmlAttributes: new { @class = "control-label col-md-6" })

                                <input type="file" name="ArchivoImagenCuerpo" class="form-control-file" accept="image/*" />
                                @Html.ValidationMessageFor(model => model.ArchivoImagenCuerpo, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-6">
                                @Html.LabelFor(model => model.Tolerancia, htmlAttributes: new { @class = "control-label col-md-6" })

                                @Html.EditorFor(model => model.Tolerancia, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Tolerancia, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label style="color:red;">Los campos con * son requeridos</label>
                        <div class="col-md-offset-2 col-md-10">
                            @Html.HiddenFor(model => model.ProductoID)
                            <input type="submit" value="Editar" class="btn btn-primary" />
                            @Html.ActionLink("Regresar", "Index", null, new { @class = "btn btn-primary" })
                        </div>
                    </div>
                </div>
                }

            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}